### ISSUE TITLE
YouTube embed breaks theme in Hugo version

### ISSUE THREAD

**Issue by guyjames** [stackbithq/stackbit-theme-fjord#9]
When using the Hugo shortcode for embedding YT videos, the left sidebar is just blank, no image or text, just a plain colour, [as here](https://guyjames.com/2011/12/23/why-do-santas-reindeer-fly-a-video-by-guy-james/).

**Comment by TomasBankauskas** [comment]
Hi @guyjames,

the Fjord theme uses reframe.js plugin to make video embeds responsive. It looks for iframe width and height attributes, calculates the ratio of the embe and applies the necessary styles. Since your iframe element does not have width and height attributes, the plugin crashes. I will update the plugin code to prevent such kind of issues. In the meantime, instead of adding

```
<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;">
<iframe src="https://www.youtube.com/embed/cG3UPsC90so" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen title="YouTube Video"></iframe>
</div>
```

you can simply insert your embed like this:

`<iframe width="560" height="315" src="https://www.youtube.com/embed/cG3UPsC90so" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

**Comment by guyjames** [comment]
Thanks but I am not directly inputting HTML like that, I am using a shortcode within Hugo. When I directly use either of the examples of code you quote here, the video does not show at all. 

I will see if it's possible to modify the code for the YT embed shortcode within Hugo.
